apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: seahorse-nodejs 
  janus-idp.io/tekton: seahorse-nodejs
  backstage.io/kubernetes-id: seahorse-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: seahorse-nodejs
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  